# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: v2.8.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1Link(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'scope': 'str',
        'url': 'str'
    }

    attribute_map = {
        'name': 'name',
        'scope': 'scope',
        'url': 'url'
    }

    def __init__(self, name=None, scope=None, url=None):  # noqa: E501
        """V1alpha1Link - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._scope = None
        self._url = None
        self.discriminator = None

        self.name = name
        self.scope = scope
        self.url = url

    @property
    def name(self):
        """Gets the name of this V1alpha1Link.  # noqa: E501

        The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\"  # noqa: E501

        :return: The name of this V1alpha1Link.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1Link.

        The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\"  # noqa: E501

        :param name: The name of this V1alpha1Link.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def scope(self):
        """Gets the scope of this V1alpha1Link.  # noqa: E501

        Either \"workflow\" or \"pod\"  # noqa: E501

        :return: The scope of this V1alpha1Link.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this V1alpha1Link.

        Either \"workflow\" or \"pod\"  # noqa: E501

        :param scope: The scope of this V1alpha1Link.  # noqa: E501
        :type: str
        """
        if scope is None:
            raise ValueError("Invalid value for `scope`, must not be `None`")  # noqa: E501

        self._scope = scope

    @property
    def url(self):
        """Gets the url of this V1alpha1Link.  # noqa: E501

        The URL. May contain \"${metadata.namespace}\" and \"${metadata.name}\".  # noqa: E501

        :return: The url of this V1alpha1Link.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1alpha1Link.

        The URL. May contain \"${metadata.namespace}\" and \"${metadata.name}\".  # noqa: E501

        :param url: The url of this V1alpha1Link.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1Link, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
